#include "request.h"
#include <iostream>
#include <random>
#include <string>

Request::Request(){
    ip_in = generate_ipv4_address();
    ip_out = generate_ipv4_address();

    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<> dis(2, 500);
    time = dis(gen);
}



// Function generated by ChatGPT
std::string Request::generate_ipv4_address() {
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<> dis(0, 255);

  return std::to_string(dis(gen)) + "." + std::to_string(dis(gen)) + "." + std::to_string(dis(gen)) + "." + std::to_string(dis(gen));
}

